plugins {
    id 'fabric-loom' version '1.9-SNAPSHOT'
}

archivesBaseName = project.archives_base_name
version = "${project.mod_version}-${project.minecraft_version}-Fabric"
group = project.maven_group

repositories {
    mavenLocal()
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.minecraft_version}+build.${project.yarn_mappings_version}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}+${project.minecraft_version}"
    include (modImplementation "org.hendrix:HendrixCore-Fabric:${project.hendrixcore_version}-${project.minecraft_version}") { changing = true }
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand  "version": project.version,
                "mod_id": project.mod_id,
                "mod_name": project.mod_name,
                "mod_description": project.mod_description,
                "mod_author": project.mod_author,
                "mod_url": project.mod_url,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version,
                "java_version": project.java_version
    }
}

tasks.withType(JavaCompile).configureEach {
    sourceCompatibility = project.java_version
    targetCompatibility = project.java_version
}

java {
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}"}
    }
}