modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"
issueTrackerURL="https://github.com/JimiIT92/BlazersMod/issues"
[[mods]]
modId = "blazersmod"
version = "${mod_version}-${minecraft_version}-Forge"
displayName = "Blazers Mod"
displayURL="https://github.com/JimiIT92/BlazersMod"
logoFile="icon.png"
credits="Idea and textures by ErenBlaze | Beta tested by Francy Pugliese"
authors = "JimiIT92"
description = '''
A Minecraft mod made for ErenBlaze and his community
'''
[[dependencies.blazersmod]]
modId = "forge"
mandatory = true
versionRange = "${loader_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.blazersmod]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"