modLoader = "javafml"
loaderVersion = "[44,)"
license = "MIT"
issueTrackerURL="https://github.com/JimiIT92/BlazersMod/issues"
[[mods]]
modId = "blazersmod"
version = "1.3-1.19.3-Forge"
displayName = "Blazers Mod"
displayURL="https://github.com/JimiIT92/BlazersMod"
logoFile="icon.png"
credits="Idea and textures by ErenBlaze | Beta tested by Francy Pugliese"
authors = "JimiIT92"
description = '''
A Minecraft mod made for ErenBlaze and his community
'''
[[dependencies.blazersmod]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.blazersmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.20)"
ordering = "NONE"
side = "BOTH"